### ISSUE TITLE
Type validation when using variables

### ISSUE THREAD

**Issue by IcanDivideBy0** [Cardinal90/graphql-union-input-type#2]
Hello,
When using variables in query, the inputType never get validated.
Assuming we're using your Star Wars schema, the following will work, whatever the `side` input in variables :

``` js
var HeroInputType = UnionInputType({
    name: 'hero',
    inputTypes: [JediInputType, SithInputType], //an object can be used instead to query by names other than defined in these types
    typeKey: 'side'
});

[...]

graphql(Schema, `
  mutation($hero: HeroInputType!) {
    hero(input: $hero) {
      ...
    }
  }
`, {}, {}, {
  hero: {
    side: 'WHATEVER'
  }
});
```

**Comment by Cardinal90** [comment]
Last line of the [Documentation](http://graphql.org/docs/api-reference-utilities/#isvalidliteralvalue): "Note that this only validates literal values, variables are assumed to provide values of the correct type." While it is possible to check a literal value, I don't see a way to access variable values during validation. Seems to be a limitation of this method.

If you really need it, the only option I see is to somehow manually insert a variable into the query string on the server before calling `graphql` function. Did not try it, there could be some caveats.

**Comment by taion** [comment]
Perhaps I'm misunderstanding, but couldn't you do this in `parseValue`?

**Comment by maddijoyce** [comment]
Hi Cardinal90, I managed to get this going in parseValue as taion mentioned. I'm not sure if the way I did it was particularly correct, but I did it like this:
```javascript
parseValue: function(value) {
	var inputType, ast;
	if (typeKey && value[typeKey]) {
		inputType = referenceTypes[value[typeKey]];
	}
	ast = astFromValue(value, inputType);
	return valueFromAST(ast, inputType);
},
```

Obviously this requires you to only use the typeKey method, but I assume it could be made to work with the other techniques as well?

**Comment by Cardinal90** [comment]
Hello. Sorry for not replying for some time.
Seems that I didn't do my research properly. You were right. I updated the package, it should fully support variables.
Please note, that you need to use the type name (`name` option) as the variable type, and not a variable name. For example, in IcanDivideBy0's message it should have been `mutation($hero: hero!)`.

On another note, graphql-js 0.10.1 broke my tests. I reported this [here](https://github.com/graphql/graphql-js/issues/910). It shouldn't cause any real problems, at least if your inputs don't have mistakes in them.
