### ISSUE TITLE
Can it be used with types defined only as string literals?

### ISSUE THREAD

**Issue by jay-jlm** [Cardinal90/graphql-union-input-type#6]
In my code (server-side only) and I'm not creating any types with Javascript, I do evrything in string literals or .graphql files.
From the ReadME file it is not immediately clear that I can, thanks.

**Comment by Cardinal90** [comment]
Not sure if there is a way. To be honest, I haven't used graphql in a year, and even then just played around with a new interesting tool. Never really got to these fancy ways of defining schemas.

I would imagine you have to call `UnionInputType` manually and then use the `name` option you provided to it like any other type's name. But to create it in the first place you have to pass `GraphQLInputObjectType` instances of the types you want to include. If the tool you use to describe schemas doesn't provide access to those, I don't see any way to do it.
