### ISSUE TITLE
Types not resolved when passing in part of an object as a variable

### ISSUE THREAD

**Issue by joeldouglass** [Cardinal90/graphql-union-input-type#7]
I've tried many combinations of implementing `resolveTypeFromAst`, `resolveType`, `resolveTypeFromValue`, but none of these seem to work when passing in just the `name` argument, for instance.

```
var query = `mutation($name: String) {
  hero(input: {
    name: $name,
    side: "jedi"
  })
}`;
```

I get an error along the lines of: 
>Expected type "hero", found {name: $name, side: "jedi"}.

This works fine if you query directly with no variables:

```
`mutation {
  hero(input: {
    name: "foo",
    side: "jedi"
  })
}`;
```

Any help would be appreciated!

**Comment by Cardinal90** [comment]
Yes, the only way is to pass a whole object as a variable like this:
```js
var query = `
	mutation($hero: heroUnion!) {
		hero(input: $hero)
	}
`;
```
To be honest, I haven't touched GraphQL in a long time. I don't remember if it is normally possible to pass a part of a custom type as a variable. Anyway, I also tried to do it your way when coding the last version, and haven't managed to make it work.

**Comment by joeldouglass** [comment]
I dug into it a bit more and I think you're right. It can't be done -- at least with a custom GraphQLScalarType. Graphql calls the `parseLiteral` method, but does not provide the variable values, just the variable names and types.
