### ISSUE TITLE
Update graphql dependency

### ISSUE THREAD

**Issue by pukapukan** [Cardinal90/graphql-union-input-type#8]
Thank you for making an awesome project!

It seems like graphql-union-input-type still has graphql 0.10 as the dependency.

Any plan on updating the graphql dependency version?

**Comment by Cardinal90** [comment]
Done. Thank you for reminding. Made it <0.13. It is probably safe to just write <1.0 and be done with it, but something might theoretically break.

I don't actually follow graphql these days, so unless someone creates an issue or a pull request, I don't update.

**Comment by pukapukan** [comment]
superb! thanks!
