### ISSUE TITLE
Is there a way to integrate this with Apollo Server

### ISSUE THREAD

**Issue by SamD** [Cardinal90/graphql-union-input-type#9]
I just started with graphql (and apollo for that matter), apollo makes use of custom resolvers and doesn't explicitly deal with creating new Graph* types normally as far as I can tell. This is certainly something I would like to be able to do though, specifically passing a list of unions.

**Comment by Cardinal90** [comment]
I haven't actually used graphql myself in a long time, so it is hard to say.

When my module's function `UnionInputType` is called, it actually creates a `GraphQLScalarType` under the hood and returns it. After briefly looking at apollo docs, I think [this section](https://www.apollographql.com/docs/graphql-tools/scalars.html#graphqlscalartype) may be relevant. You'd have to create a union input type the usual way and use the returned value as a resolver. There may be some caveats though, I haven't tested it.

**Comment by SamD** [comment]
Thanks for the response and pointer, I'll take a look

**Comment by jide** [comment]
In case someone wants to do this, here is how to do : 
```js
let schema;

const MyUnionInputType = UnionInputType({
  name: "MyUnionInputType",
  resolveType(name) {
    // The important part: return the type from the schema from its name (e.g. "FirstInputType")
    return schema.getTypeMap()[name];
  },
  typeKey: "type"
});

const typeDefs = `
scalar MyUnionInputType

type Query {
  fake: Boolean
}

type Mutation {
  mymutation(
    myarg: MyUnionInputType
  ): Boolean
}

input FirstInputType {
  type: String!
  something: String!
}

input SecondInputType {
  type: String!
  otherthing: String!
}
`;

const resolvers = {
  Query: {
    fake() {
      return true;
    }
  },
  Mutation: {
    mymutation() {
      return true;
    }
  },
  MyUnionInputType
};

schema = makeExecutableSchema({ typeDefs, resolvers });
```

**Comment by simoneb** [comment]
In graphql 15 this package no longer works as the isValidLiteralValue function no longer exists. Removing it from the source code seems to keep it in a somewhat working state though.
